repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
      exclude: (?x)(^(?!src/azureiai-).*|.*/tests/)
      args:
      - "--line-length"
      - "120"
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
